name: Deploy Astrologer WordPress Theme to Live Server

on:
  push:
    branches:
      - master

jobs:
  web-deploy:
    name: 🎉 Deploy Theme Changes via FTP/SFTP
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: 📂 Sync files to Live WordPress Server
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: ${{ secrets.FTP_PORT || 21 }}
          protocol: ${{ secrets.FTP_PROTOCOL || 'ftp' }}
          local-dir: ./wp-content/themes/astrologer-theme/
          server-dir: /public_html/wp-content/themes/astrologer-theme/
          dangerous-clean-slate: false
